import schemathesis

@schemathesis.hooks.register
def before_call(context, request):
    # Add a custom header to all requests generated by Schemathesis
    request.headers["X-Test-ID"] = "schemathesis-run"
    return request

@schemathesis.hooks.register
def after_call(context, response, case):
    # Custom validation logic after each call
    if response.status_code == 500:
        raise ValueError("Server error detected!")
