openapi: 3.1.0
info:
  title: Redocly API
  version: 1.0.0
  summary: Redocly API summary
  license:
    name: MIT
    identifier: MIT
security:
  - basicAuth: []
servers:
  - url: https://api.acme.com
paths:
  /docs:
    get:
      summary: Get docs
      operationId: getDocs
      responses:
        '200':
          description: Returns documentation info
        '404':
          description: Not found
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
